CREATE DATABASE TherapyDB;
USE TherapyDB;
-- Table 1: Users
CREATE TABLE Users (
    UserID INT IDENTITY(1,1) PRIMARY KEY,
    Email NVARCHAR(100) UNIQUE NOT NULL,
    [Password] NVARCHAR(100) NOT NULL,
    IsAdmin BIT NOT NULL DEFAULT 0
);

-- Table 2: Therapists
CREATE TABLE Therapists (
    TherapistID INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(100) NOT NULL,
    Email NVARCHAR(100) NOT NULL
);

-- Table 3: Therapies
CREATE TABLE Therapies (
    TherapyID INT IDENTITY(1,1) PRIMARY KEY,
    TherapyName NVARCHAR(100) NOT NULL,
    Price DECIMAL(18,2) NOT NULL
);

-- Table 4: Bookings

CREATE TABLE Bookings (
    BookingID INT IDENTITY(1,1) PRIMARY KEY,
    UserID INT NOT NULL,
    TherapistID INT NOT NULL,
    TherapyID INT NOT NULL,
    SessionDate DATE NOT NULL,
    StartTime TIME NOT NULL, 
    EndTime TIME NOT NULL,   
    PaymentScreenshot NVARCHAR(MAX),
    GoogleMeetLink NVARCHAR(MAX),
    Status NVARCHAR(50) NOT NULL DEFAULT 'Pending',

    CONSTRAINT FK_Bookings_Users FOREIGN KEY (UserID) REFERENCES Users(UserID),
    CONSTRAINT FK_Bookings_Therapists FOREIGN KEY (TherapistID) REFERENCES Therapists(TherapistID),
    CONSTRAINT FK_Bookings_Therapies FOREIGN KEY (TherapyID) REFERENCES Therapies(TherapyID)
);



-- A. Insert Users (Admin + Dummy Clients for testing)
INSERT INTO Users (Email, [Password], IsAdmin) VALUES 
('admin@edchat.pk', 'Admin123', 1),
('client.one@gmail.com', 'pass123', 0),
('client.two@gmail.com', 'pass123', 0),
('client.three@gmail.com', 'pass123', 0);

-- B. Insert Therapies
INSERT INTO Therapies (TherapyName, Price) VALUES
('Cognitive Behavioral Therapy (CBT)', 3500.00),
('Speech & Language Therapy', 3000.00),
('Play Therapy', 2500.00),
('Family & Relationship Therapy', 4500.00);

-- C. Insert Therapists (All doctors from original list)
INSERT INTO Therapists (Name, Email) VALUES
('Dr. Ali', 'ali@mindcare.pk'),
('Dr. Sara', 'sara@mindcare.pk'),
('Dr. Zeeshan', 'zeeshan@mindcare.pk'),
('Dr. Atif', 'atif@mindcare.pk'),
('Dr. Aisha', 'aisha@mindcare.pk'),
('Dr. Hina', 'hina@mindcare.pk'),
('Dr. Asif', 'asif@mindcare.pk'),
('Dr. Mariyam', 'mariyam@mindcare.pk'),
('Dr. Ahmed', 'ahmed@mindcare.pk'),
('Dr. Ashfaq', 'ashfaq@mindcare.pk'),
('Dr. Asna', 'asna@mindcare.pk'),
('Dr. Subhana', 'subhana@mindcare.pk');

-- D. Insert Bookings (Dummy data to make Queries work)
INSERT INTO Bookings (UserID, TherapistID, TherapyID, SessionDate, StartTime, EndTime, Status) VALUES
(2, 1, 1, '2023-12-01', '14:00', '15:30', 'Confirmed'), -- Client 1, Dr. Ali, CBT
(2, 2, 4, '2023-12-05', '10:00', '11:00', 'Pending'),   -- Client 1, Dr. Sara, Family Therapy
(3, 1, 1, '2023-12-06', '09:00', '10:30', 'Confirmed'), -- Client 2, Dr. Ali, CBT
(4, 12, 2, '2023-12-07', '16:00', '17:00', 'Confirmed'); -- Client 3, Dr. Subhana, Speech Therapy


SELECT 
    B.BookingID,
    U.Email AS ClientEmail,
    T.Name AS TherapistName,
    TH.TherapyName,
    TH.Price,
    B.SessionDate,
    B.StartTime,
    B.EndTime
FROM Bookings B
INNER JOIN Users U ON B.UserID = U.UserID
INNER JOIN Therapists T ON B.TherapistID = T.TherapistID
INNER JOIN Therapies TH ON B.TherapyID = TH.TherapyID
WHERE B.Status = 'Confirmed';
GO

-- REQUIREMENT 2: SUBQUERY (WHERE Clause)
-- Description: Find all Clients (Users) who have booked the most expensive therapy type available.
SELECT UserID, Email 
FROM Users 
WHERE UserID IN (
    SELECT UserID 
    FROM Bookings 
    WHERE TherapyID = (
        SELECT TOP 1 TherapyID 
        FROM Therapies 
        ORDER BY Price DESC
    )
);

-- REQUIREMENT 3: SUBQUERY (Derived Table)
-- Description: Calculate total revenue generated by each Therapist.
SELECT 
    T.Name AS TherapistName,
    ISNULL(RevenueTable.TotalEarned, 0) AS TotalRevenue
FROM Therapists T
LEFT JOIN (
    SELECT 
        TherapistID, 
        SUM(TH.Price) AS TotalEarned
    FROM Bookings B
    JOIN Therapies TH ON B.TherapyID = TH.TherapyID
    WHERE B.Status = 'Confirmed'
    GROUP BY TherapistID
) AS RevenueTable ON T.TherapistID = RevenueTable.TherapistID;